language: swift
osx_image: xcode8
podfile: Podfile
notifications:
  email: false
before_install:
- gem install cocoapods
- pod install --repo-update

script:
- xcodebuild -workspace CryptoTick.xcworkspace -scheme CryptoTick build test | xcpretty -c && exit ${PIPESTATUS[0]}
after_success:
  - bash <(curl -s https://codecov.io/bash)
