language: objective-c
osx_image: xcode8
podfile: Podfile
notifications:
  email: false
before_install:
- gem install cocoapods
- pod install

script:
- xcodebuild test -workspace CryptoTick.xcworkspace -scheme CryptoTick | xcpretty -c && exit ${PIPESTATUS[0]}
